### ISSUE TITLE
"trace = TRUE" results in "variational_fit" error

### ISSUE THREAD

**Issue by l0ka** [caravagn/VIBER#1]
Hi @caravagn, I noticed that when I set `trace = TRUE` in the `variational_fit` step it fails, resulting in this error:
```
[easypar] 10/10 computations returned errors and will be removed.
Error in sum(errs) : invalid 'type' (list) of argument
```
Specifically, the issue seems to be coming from [here](https://github.com/caravagnalab/VIBER/blob/master/R/Fit_variational.R), the piece of code starting at row 286: 
```
if(save_trace) {
      fit_trace = bind_rows(fit_trace,
                            tibble(
                              cluster.Binomial = labels,
                              step = i))
}
```
Replacing with `cluster.Binomial = unlist(labels)` seems to solve the problem but I'm not sure that's what you were looking for. 
That's the code I used (with VIBER version: `VIBER_0.1.0`):
```
library(VIBER)
data(mvbmm_example)
variational_fit(x     = mvbmm_example$successes,
                y     = mvbmm_example$trials,
                trace = TRUE)
```
Thanks!

**Comment by caravagn** [comment]
Thanks, you were right. I fixed that now.

G
